name: Publish UOS V20 Docker image

on:
  workflow_dispatch:

jobs:
  build_and_push:
    strategy:
      matrix:
        OS_DIFF: [1070]

    name: Build and push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          build-args: |
            OS_DIFF=${{ matrix.OS_DIFF }}
          file: ./uos_v20.sys.Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/uos:v20-${{ matrix.OS_DIFF }}
